Refactor Executor (#1435)
* Refactor Executor

Executor uses a single control loop aio task per Function Executor.
This allows to do all the decision making in a single async task
and thus implement complex control logic without concurrency related
bugs and overcomplications. All the long running aio operations are
done outside of the control loop aio task. When completed the
operations add an event with the results of the operation to control
loop event queue.

Also use Click library for CLI arguments.

* Don't re-add Function Executor to reported Executor state on FE shutdown

This is a bugfix.

* Add FunctionExecutorTerminationReason to reported Executor state

This should allow Server to decide what to do when a Function
Executor gets terminated on Executor side.

* Use _termination_reason_to_short_name dict to improve code formatting

* Fix code formatting resulting in Executor startup failure

We can't use proto enums in Dict[K, V] type annotations.

* Showing the server desired state in the fe object in the executor list

---------

Co-authored-by: Diptanu Gon Choudhury <diptanuc@gmail.com>

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -173,11 +173,10 @@ jobs:
               sleep 1
             done
           done
-      # TODO: Uncomment once the bug with FE shutdowns is fixed
-      # - name: Validate that all processes terminated
-      #   run: |
-      #     if pgrep -f indexify; then
-      #       echo "Error: Some Indexify processes are still running."
-      #       ps aux | grep indexify
-      #       exit 1
-      #     fi
+      - name: Validate that all processes terminated
+        run: |
+          if pgrep -f indexify; then
+            echo "Error: Some Indexify processes are still running."
+            ps aux | grep indexify
+            exit 1
+          fi
